development:
  CLOUDINARY_CLOUD_NAME: "dg1doueiz"
  CLOUDINARY_API_KEY: "992267637796444"
  CLOUDINARY_API_SECRET: "5u0sxTPD8YS2XGEn1SXt9SF1sqs"
  secure: true

production:
  CLOUDINARY_CLOUD_NAME: "dg1doueiz"
  CLOUDINARY_API_KEY: "992267637796444"
  CLOUDINARY_API_SECRET: "5u0sxTPD8YS2XGEn1SXt9SF1sqs"
  secure: true
